version: "3.9"  # optional since v1.27.0
services:
  btpsimple_src:
    container_name: btp_src
    environment:
      - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_src
      - BTPSIMPLE_CONFIG=/btpsimple/config/src.config.json
      - BTPSIMPLE_SRC_ADDRESS=/btpsimple/config/btp.src
      - BTPSIMPLE_SRC_ENDPOINT=http://goloop:9080/api/v3/src
      - BTPSIMPLE_DST_ADDRESS=/btpsimple/config/btp.dst
      - BTPSIMPLE_DST_ENDPOINT=http://goloop:9080/api/v3/dst
      - BTPSIMPLE_OFFSET=/btpsimple/config/offset.src
      - BTPSIMPLE_KEY_STORE=/btpsimple/config/src.ks.json
      - BTPSIMPLE_KEY_SECRET=/btpsimple/config/src.secret
      - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/data/log/btpsimple_src.log
    healthcheck:
      test: bash -c "[ -f /btpsimple/config/src.config.json ]"

