version: '3.8'

services:

  hmny:
    image: ${docker_registry}/hmny:latest
    container_name: ixh_hmny
    restart: unless-stopped
    ports:
      - 9500:9500 # s0 rpc: one node
      - 5099:5099 # s0 explorer
      # - 9800-9809 # websocket
    networks:
      - nodes

  icon:
    image: ${docker_registry}/icon:latest
    container_name: ixh_icon
    restart: unless-stopped
    ports:
      - 9080:9080
    networks:
      - nodes

  bmr:
    image: ${docker_registry}/bmr:latest
    container_name: ixh_bmr
    restart: unless-stopped
    ports:
      - 6060:6060 # golang pprof
    networks:
      - bmr
    entrypoint: ["/bin/bash", "-c"]
    command:
    - |
      echo '$bmr_config_json' >/config.json
      /bin/btpsimple -config /config.json

networks:
  bmr:
    name: bmr
  nodes:
    name: nodes
