name: Javascore BTS
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'master'
      - 'beta-cicd'
    paths:
      - 'javascore/bts'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 11

      - name: Build javascore bts
        working-directory: ./javascore
        run: gradle bts:build

      - name: Run javascore bts tests
        working-directory: ./javascore
        run: gradle bts:test

      - name: Generate optimizedJar
        working-directory: ./javascore
        run: |
             gradle bts:optimizedJar
